server.port: 9000

spring:
  application:
    name: user-service
  # when running multiple spring boot in single jvm, need to set jmx
  jmx:
    default-domain: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: password1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    user: #service account
      name: service
      password: password
      roles: SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring.session.store-type: redis # Session store type.
spring.redis.host: 192.168.56.101 # Redis server host.
spring.redis.port: 6379 # Redis server port.
