server:
  port: 8761

spring:
  application:
    name: eureka-server
  # when running multiple spring boot in single jvm, need to set jmx
  jmx:
    default-domain: eureka-server
  # when deploy to jboss, need to set below value  
  freemarker:
    prefer-file-system-access: false
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
