server:
  port: 8761

spring:
  application:
    name: eureka
  freemarker:
    prefer-file-system-access: false
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
