server.port: 8082
# set the context path so that it doesn’t use the default ("/") 
# because otherwise you can get cookies for other servers on localhost being sent to the wrong server
server.servlet.context-path: /uaa

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true
    username: root
    password: password1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  oauth:
    token-store: jwt
    jwt:
      #key-type: secret
      #sign-key: 123
      key-type: public
      key-store:
        file: mytest.jks
        password: mypass
        key: mytest
 